# This is a sample Python script generated by MockLLM
import pandas as pd

def perform_analysis():
    print("Mock analysis: Loading and displaying dummy data...")
    data = {'column_A': [10, 20, 30], 'column_B': ['X', 'Y', 'Z']}
    df = pd.DataFrame(data)
    print(df.head())
    print("Mock analysis complete.")

if __name__ == '__main__':
    perform_analysis()